### ISSUE TITLE
Windows OS - node-mongo cli error on install

### ISSUE THREAD

**Issue by KeithanPhilander** [code-collabo/node-mongo-cli#126]
When running node-mongo I'm prompted with choosing a folder name and then choosing a template either cjs or esm
I choose cjs and it spits out this error

node:events:355
throw er; // Unhandled 'error' event
Error: spawn npm ENOENT
at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
at onErrorNT (node:internal/child_process:480:16)
at processTicksAndRejections (node:internal/process/task_queues:81:21)
Emitted 'error' event on ChildProcess instance at:
at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
at onErrorNT (node:internal/child_process:480:16)
at processTicksAndRejections (node:internal/process/task_queues:81:21) {
errno: -4058,
code: 'ENOENT',
syscall: 'spawn npm',
path: 'npm',
spawnargs: [ 'install' ]
}

I can bypass this error by downloading template straight from github instead of using the CLI

OS: Windows 10 64bit
node version: 15.11.0
npm version: 6.14.11

**Comment by Ifycode** [comment]
Thank you @KeithanPhilander Was hoping you would help me document it here as you have found this out. Thank you. I've fixed the Windows OS issue. Will link up the PR here and let you know when I've published it so that you will be able to install it afterwards.

**Comment by Ifycode** [comment]
@KeithanPhilander uninstall the package and reinstall as you did before. The cli install should now work 💯

**Comment by Ifycode** [comment]
Reopening because for some reason new version 1.0.1 doesn't yet show up on npm  even though it says it's published... Keeping this issue open till this is resolved.

**Comment by Ifycode** [comment]
Closing this, since it's now published @KeithanPhilander you can now uninstall the CLI and install globally again. It now works on windows.
