### ISSUE TITLE
CLI: Change default folder name to something shorter

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo-cli#153]
#### Task description
In the CLI, the default folder name is descriptive but seems too long. Change the defaultFolderName from `node-mongo-kit` to `nm-kit`.

> Hint: Look for defaultFolderName in prompts/foldername.js file.

**Comment by rashidmya** [comment]
I'd like to work on this issue if no one is yet

**Comment by Ifycode** [comment]
Yes. Please do. Thank you! Create a new branch from develop branch and send a pull request to develop. Let me know if you still need clarification on anything.

**Comment by Ifycode** [comment]
Yes. Please do. Thank you! @rashidmya  
Create a new branch from develop branch and send a pull request to develop. Let me know if you still need clarification on anything.
