### ISSUE TITLE
Documentation: Update heading and remove intro for boilerplate template page

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo-cli#171]
#### Task description
In the [boilerplate template docs](https://code-collabo.gitbook.io/node-mongo/boilerplate-templates):
- Change the page heading to "API boilerplate templates".
- Remove the introductory paragraph and the 3 list items below it.

> Find the file to edit in the doc folder inside the root of this cli repo.

**Comment by HritikR** [comment]
Hi @Ifycode, Can you please assign this to me.

**Comment by Ifycode** [comment]
Yes, please. Go ahead.  Assigned to you @HritikR
