### ISSUE TITLE
Documentation: Add readme and content for typescript boilerplate template repo

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo-cli#178]
#### Task description
The typescript API boilerplate template repo has now been created (hurray!), but it doesn't have a readme. You are to do this:
- Create a readme file in the the root of the [typescript API boilerplate template repo](https://github.com/code-collabo/node-mongo-api-boilerplate-template-TS).
- Add content to the readme file you created. Get the correct readme heading and the development server section from the [cjs repo](https://github.com/code-collabo/node-mongo-api-boilerplate-template-CJS) and update it.

> Also remember to change "(common js)" in the readme heading to "(typescript)", since this readme is for the ts API boilerplate template.

Please also do this:
- In the [node-mongo-cli](https://github.com/code-collabo/node-mongo-cli) readme, you will find a list item - "Typescript (coming soon)". It's just before the gif image. Turn it to a link to take the reader to the [typescript API boilerplate template repo](https://github.com/code-collabo/node-mongo-api-boilerplate-template-TS) repo.

**Comment by Olaleye-Blessing** [comment]
Can I work on this? If yes, concerning the **please also do this**, does it mean I will be creating two pull requests? One to [typescript repo](https://github.com/code-collabo/node-mongo-api-boilerplate-template-TS) and the other to [node-modo-cli](https://github.com/code-collabo/node-mongo-cli)?
