### ISSUE TITLE
CLI: Make CLI create/generate .env files for templates

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo-cli#183]
#### Task description
- Write a function called **createEnvFiles**, that will create a .env file and a .env.example file at the root of the boilerplate templates generated by the CLI.
- Both the .env file and the .env.example should have the content below:
````
MONGODB_URI=
MONGODB_ATLAS_URI=
````

> You can take a clue from [solution submitted for .gitignore](https://github.com/code-collabo/node-mongo-cli/pull/148/files)

**Comment by HritikR** [comment]
HI @Ifycode , I would like to work on this.

**Comment by Ifycode** [comment]
Cool! Yes, please. Assigned to you @HritikR

**Comment by Ifycode** [comment]
Hi @HritikR, I left a review on your PR.
